backend:
  name: github
  repo: ''
  branch: main
  base_url: https://auth.marke.com.br
  commit_messages:
    create: Criado {{collection}} “{{slug}}”
    update: Atualizado {{collection}} “{{slug}}”
    delete: Deletado {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
site_url: ''
media_library:
  name: cloudinary
  config:
    cloud_name: ''
    api_key: ''
    upload_preset: 'ml_default'
    output_filename_only: false
    multiple: false
    use_transformations: true
    default_transformations:
      - fetch_format: auto
        width: 1920
        quality: auto
        crop: scale
locale: 'pt'
logo_url: ''
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
collections:   
  - name: 'site'
    label: 'Configurações Gerais'
    editor:
      preview: false
    create: false
    delete: false
    files:
      - label: 'Hooks'
        description: 'Códigos de terceiros como tags e outros scripts.'
        name: 'hooks'
        file: 'src/data/global/hooks.json'
        fields:
          - name: 'head'
            label: 'Head'
            hint: 'Código inserido antes da tag </head>'
            widget: 'code'
            default_language: 'html'
          - name: 'body'
            label: 'Body'
            hint: 'Código inserido após <body>'
            widget: 'code'
            default_language: 'html'
          - name: 'footer'
            label: 'Footer'
            hint: 'Código inserido antes de </body>, no fim do documento'
            widget: 'code'
            default_language: 'html'